/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jmr.application;

import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.xy.DefaultXYDataset;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 * Ventana que muestra la gráfica de variación
 * @author Juan Jesús Tomás Rojas
 * @version 1.0 - Mayo de 2017
 */
public class GraphInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Crea una ventana GraphInternalFrame
     * @param variations Variaciones entre frames
     * @param nombreVideo Nombre del vídeo
     */
    public GraphInternalFrame(ArrayList<Double> variations, String nombreVideo) {
        myInitComponents();
        String titulo = "Gráfica de " + nombreVideo;
        //this.setSize(new Dimension(500,500));
        JFreeChart chart = ChartFactory.createXYLineChart(titulo, "Fotograma", "Variación", createDataSet(variations), PlotOrientation.VERTICAL, false, true, false);

        
        ChartPanel cpanel = new ChartPanel(chart);    
        //cpanel.setPreferredSize(new Dimension(500,500));
        
        this.getContentPane().add(cpanel);
        this.pack();
        //this.getContentPane().add(cpanel,BorderLayout.CENTER);
        //this.add(cpanel);
    }

    /**
     * Crea el set de datos con las variaciones de frames
     * @param variations Variaciones de frames
     * @return Set de datos con las variaciones de frames
     */
    private XYDataset createDataSet(ArrayList<Double> variations){
        DefaultXYDataset dataset = new DefaultXYDataset();
        XYSeries serie = new XYSeries("XY Data");
        for(int i = 0; i < variations.size(); i++){
            serie.add((Number)i, variations.get(i));
        }        
        dataset.addSeries("Variacion", serie.toArray());        
        return dataset;
    }
    
    /**
     * Inicializa los componentes
     */
    private void myInitComponents(){
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
